config/routes.rb
LibraryOnline::Application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    devise_for :users

    resources :users do
      get 'show' => 'users#show'
    end

    resources :contacts

    root 'books#index'
    get 'contact' => 'contacts#contact', as: :contactUs

    resources :books do
      resources :comments
      collection do
        get 'available'
        get 'reserved'
        get 'all' => 'books#all'
        get 'reserve_it' => 'books#reserve_it'
        get 'render_it' => 'books#render_it'
        get 'delete' => 'books#delete'

      end
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :comments
	has_many :users, through: :comments
	has_one :page


	#Les restrictions
	validates :title, presence: true, :length => { minimum: 5 } , 
	uniqueness: {message: "The title of the book must be unique."}
	validates :author, presence: true, :length => { minimum: 5 }
	validates :synopsis, presence: true, :length => { minimum: 5 }  
	validates :note, :inclusion => {:in => (0..10), message: I18n.t('Mark_min') } 
	
	#Les scopes
	scope :available, -> { where(situation: 1) } #situation: 1 correspond aux livres disponibles
	scope :reserved, -> { where(situation: 2) } #situation: 2 correspond aux livres réservés

	#Les covers
	has_attached_file :cover, 
	 	:styles => { 
	 	 :medium => "400x200>", 
	 	 :thumb => "100x50#" 
	 	}, 
	 	:default_url => "/images/:style/missing.png"

	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :book
	belongs_to :user

	validates :book_id, presence: true
	
end

app/models/contact.rb
class Contact < ActiveRecord::Base


end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :book


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :comments
    has_many :books, through: :comments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_filter :set_locale


  def default_url_options(options={})
  	logger.debug "default_url_options is passed options: #{options.inspect}\n"
  	{ locale: I18n.locale }
  end

  private
  	def http_header_locale
  		request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  	end

  	def set_locale
  		I18n.locale = params[:locale] || http_header_locale || I18n.default_locale
  	end

end
 

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books/all
  # GET /books/all.json
  # GET /books/all.xml
  def all
    @books = Book.all
  end


  # GET /books/available
  # GET /books/available.json
  # GET /books/available.xml
  def available
    @books = Book.available
  end

  # GET /books/reserved
  # GET /books/reserved.json
  # GET /books/reserved.xml
  def reserved
    @books = Book.reserved
  end

  # GET /books/1
  # GET /books/1.json
  # GET /books/1.xml
  def show
    @comments = @book.comments
    @comment = @book.comments.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end


  def reserve_it
    @ref_book = params[:ref_book]
    @book = Book.find(@ref_book)
    @book.situation = 2
    @book.save
    redirect_to available_books_path, notice: I18n.t('books.reserved') 
  end


  def render_it
    @ref_book = params[:ref_book]
    @book = Book.find(@ref_book)
    @book.situation = 1
    @book.save
    redirect_to reserved_books_path, notice: I18n.t('books.rendered')
  end


  def delete
    @ref_book = params[:ref_book]
    @book = Book.find(@ref_book)
    @book.destroy
    redirect_to all_books_path, notice: I18n.t('books.destroyed')
  end


  # POST /books
  # POST /books.json
  def create
    @book = Book.create(book_params)
    @book.situation = 1

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: I18n.t('books.created') }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: I18n.t('books.updated') }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: I18n.t('books.destroyed') }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :synopsis, :cover, :note, :situation)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@book = Book.find(params[:book_id])
		@comment = @book.comments.new(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to @comment.book, notice: I18n.t('books.comment')
		else
			render text: 'Error!'
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :user_id)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def contact
		@contact = Contact.new
		@contacts = Contact.all
	end

	def create
		@contact = Contact.new(contact_params)

		if @contact.save
			redirect_to contactUs_path, notice: I18n.t('Mail_sent')
	  		ContactMailer.contact_email(@contact).deliver
		else
			render text: 'Error!'
		end	
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :email, :comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @books = @user.books
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end


  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book">
<ul>

<li><p><%= book.title %></p></li>
<p><%= book.author %></p>

</div>

app/views/books/_books.html.erb
<hr/>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('Title') %></th>
      <th><%= t('Author')%></th>
      <th colspan="4"></th>
    </tr>
  </thead>                                                                                                                                                                            

app/views/books/_comments.html.erb
<h2><%= t('READERS') %>/<%= t('Comments') %></h2>
<ul>
	<%= render @comments %>
</ul>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :synopsis, as: :text, input_html: {rows: 10, cols: 10} %>
    <%= f.input :note %>
    <%= f.input :cover %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/all.html.erb
<!-- All Books-->
<div class="container-book bg-grey ">
  <h1><%= t('Listing_Books') %></h1>
</div>

<%= render 'books' %>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to t('Show'), book, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to t('Edit'), edit_book_path(book), class: 'btn btn-default' %></td>
        <td><%= link_to t('Destroy'), {controller: "books", action: "delete", :ref_book => book.id}, data: { confirm: t('destroy_confirmation') },:class => 'btn btn-mini btn-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New_Book'), new_book_path, class: 'btn btn-default' %>

app/views/books/available.html.erb
<!-- Available Books-->
<div class="container-book bg-grey ">
<h1><%= t('Available_books') %></h1>
</div>

<%= render 'books' %>                                                                                                                                                                        

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to t('Show'), book, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to t('Edit'), edit_book_path(book), class: 'btn btn-default' %></td>
        <td><%= link_to t('Destroy'), book, method: :delete, data: { confirm: t('destroy_confirmation') }, class: 'btn btn-mini btn-danger' %></td>
        <td><%= link_to t('Reserve_it'), {controller: "books", action: "reserve_it", :ref_book => book.id} , :class => 'btn btn-mini btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/edit.html.erb
<h1><%= t('Editing_book') %></h1>
<hr />

<%= render 'form' %>

<%= link_to t('Show'), @book %> |
<%= link_to t('Back'), all_books_path %>

app/views/books/index.html.erb
<!-- Library Online -->
<div class="jumbotron text-center">
  <h1><%= t('Site_title') %></h1> 
  <p><%= t('Our_speciality') %></p> 
</div>

<!-- About Library Online -->
<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h2><%= t('ABOUT_LIBRARY_ONLINE') %></h2><br>

      <h4><%= t('Future_Library') %> </h4><br>
      <p><%= t('Description_About') %> </p><br>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div>

<!-- Our values-->
<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-globe logo slideanim"></span>
    </div>
    <div class="col-sm-8">
      <h2><%= t('Our_Values') %></h2><br>
      <h4><strong>MISSION:</strong><%= t('Our_Mission') %></h4><br>      
      <p><strong>VISION:</strong><%= t('Our_Vision') %></p>
    </div>
  </div>
</div>



<!-- What we offer -->
<div id="services" class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4><%= t('What_we_offer') %></h4>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>POWER</h4>
      <p><%= t('POWER') %></p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>LOVE</h4>
      <p><%= t('LOVE') %></p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>JOB DONE</h4>
      <p><%= t('JOB_DONE') %></p>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>GREEN</h4>
      <p><%= t('GREEN') %></p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>CERTIFIED</h4>
      <p><%= t('CERTIFIED') %></p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench logo-small"></span>
      <h4 style="color:#303030;">HARD WORK</h4>
      <p><%= t('HARD_WORK') %></p>
    </div>
  </div>
</div>



<!-- What our customers says -->
<div class="container-fluid text-center bg-grey">
	 <h2><%= t('What_our_customers_say') %></h2>
	<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
	    <h4><%= t('Notice1') %><br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
	    </div>
	    <div class="item">
	      <h4><%= t('Notice2') %><br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
	    </div>
	    <div class="item">
	      <h4>"<%= t('Notice3') %><br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
	    </div>
	  </div>

	  <!-- Left and right controls -->
	  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
</div>

app/views/books/new.html.erb
<div class="container-book bg-grey ">
<h1><%= t('New_book') %></h1>
</div>

<hr/>

<%= render 'form' %>

<%= link_to t('Back'), all_books_path %>

app/views/books/reserved.html.erb
<div class="container-book bg-grey ">
<h1><%= t('Reserved_books') %></h1>
</div>

<%= render 'books' %>   

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to t('Show'), book, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to t('Edit'), edit_book_path(book), class: 'btn btn-default' %></td>
        <td><%= link_to t('Destroy'), book, method: :delete, data: { confirm: t('destroy_confirmation') }, class: 'btn btn-mini btn-danger' %></td>
        <td><%= link_to t('Render_it'), {controller: "books", action: "render_it", :ref_book => book.id} , :class => 'btn btn-mini btn-warning' %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>


app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<hr />

<p>
  <strong><%= t('author_show') %></strong>
  <%= @book.author %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @book.synopsis %>
</p>

<p>
  <strong><%= t('mark') %></strong>
  <%= @book.note %>
</p>


<p>
  <strong><%= t('cover') %></strong>
</p>
<%= image_tag @book.cover.url(:medium) %>

<p>
<%= link_to t('Edit'), edit_book_path(@book) %> |
<%= link_to t('Back'), all_books_path %>
</p>

<hr />
<%= render 'comments' %>
<hr />

<h2><%= t('New_comment') %></h2>
<%= render 'comments/form' %>
</br>

app/views/comments/_comment.html.erb
<% if comment.message != nil %>
<li><strong><%= link_to comment.user.email, comment.user %></strong></li>
<p><%= comment.message %></p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@book, @comment] do |f| %>

	<%= f.hidden_field :book_id %>
	<%= f.text_area :message, :placeholder => "Message" %>
	<br />
	<%= f.submit %>
<% end %>

app/views/contacts/contact.html.erb
<!-- About us-->

<div class="jumbotron text-center">
<h2><%= t('ABOUT_US') %></h2><br>
<p><%= t('Students') %></p>
<p><%= t('Love_Rails') %></p> 
</div>
<br>

<div class="container-fluid text-center">
	<div class="row">
	  <div class="col-sm-6">
	    <p class="text-center"><strong>Elisabeth</strong></p><br>
	    <a href="#demo" data-toggle="collapse">
	      <img src="/eli.jpg" class="img-circle person" alt="Random Name">
	    </a>
	    <div id="demo" class="collapse">
	      <p><%= t('Elisabeth1') %></p>
        <p><%= t('Elisabeth2') %></p>
	      <p><%= t('Elisabeth3') %></p>
	      <p><%= t('Elisabeth4') %></p>
	    </div>
	  </div>

	  <div class="col-sm-6">
	    <p class="text-center"><strong>Maxime</strong></p><br>
	    <a href="#demo2" data-toggle="collapse">
	      <img src="/maxime.jpg" class="img-circle person" alt="Random Name">
	    </a>
	    <div id="demo2" class="collapse">
	      <p><%= t('Maxime1') %></p>
	      <p><%= t('Maxime2') %></p>
	      <p><%= t('Maxime3') %></p>
	    </div>
	  </div>
	</div>
</div>

<!-- Contact -->
<div class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5">
      <p><%= t('Contact24H') %></p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Ivry-Sur-Seine, FRANCE</p>
      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
      <p><span class="glyphicon glyphicon-envelope"></span> duong.elisabeth@gmail.com</p>
    </div>
    <div class="col-sm-7">
        <%= form_for @contact do |f| %>
        <div class="col-sm-6 form-group">
          <%= f.text_field :name , :class=>'form-control', :placeholder=>'Name', :type=>'text', :required=> 'true' %>
        </div>
        <div class="col-sm-6 form-group">
          <%= f.text_field :email, :class=>'form-control', :placeholder=>'Email', :type=>'text', :required=> 'true' %>
        </div>
        <div class="col-sm-12 form-group">
          <%= f.text_area :comment, :class=>'form-control', :placeholder=>'Comment', :rows=>'5', :required=> 'true' %><br>
        </div>
      <div class="row">
        <div class="col-sm-12 form-group">
          <%= f.submit t('Send'), :class => 'btn btn-default pull-right', url:{controller: "contacts", action: "send_mail"}%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>


 <!-- Google maps -->
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2627.3051708120993!2d2.3756389508128106!3d48.81423851166747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e673cccf5cb859%3A0x10ff8b28c767ad3f!2sESIEA+Paris-Ivry+-+Ecole+d&#39;ing%C3%A9nieurs+du+num%C3%A9rique!5e0!3m2!1sfr!2sfr!4v1449598042581" width="100%" height="400px" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/layouts/_header.html.erb
<div class="row">
	<nav class="span12">
		<div class="navbar">
			<div class="navbar navbar-inverse">
				<ul class="nav navbar-nav">
					<li class="divider-vertical"></li>

					<li><%= link_to t('Menu_title').html_safe, root_path %></li>
					<li><%= link_to t('Home').html_safe, root_path %></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('Books')%><span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to t('All_Books_html').html_safe, all_books_path %></li>
							<li><%= link_to t('Available_html').html_safe, available_books_path %></li>
							<li><%= link_to t('Reserved_html').html_safe, reserved_books_path %></li>
							<li><%= link_to t('Add_html').html_safe, new_book_path %></li>
						</ul>
					</li>
					<li><%= link_to t('Users'), users_path %></li>
					<li><%= link_to t('Contact_us'), contactUs_path %></li>
				</ul>
				<ul class="navbar-text pull-right">
					<% if user_signed_in? %>
					  <%= t('Logged_in_as') %><strong><%= current_user.email %></strong>.
					  <%= link_to t('Edit_profile'), edit_user_registration_path, :class => 'navbar-link' %> |
					  <%= link_to t("Log_Out"), destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</div>


app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="row">
		<div class="span12">
			<div class="alert alert-warning <%= key %> "><%= value.html_safe %></div>
		</div class>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('Site_title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <style>
    body {
    font: 400 15px Lato, sans-serif;
    line-height: 1.8;
    }
  footer .glyphicon {
    font-size: 20px;
    margin-bottom: 20px;
    color: #f4511e;
  }

  h2 {
    font-size: 24px;
    text-transform: uppercase;
    color: #303030;
    font-weight: 600;
    margin-bottom: 30px;
  }
  h4 {
    font-size: 19px;
    line-height: 1.375em;
    color: #303030;
    font-weight: 400;
    margin-bottom: 30px;
  }  
  .container-fluid {
  	padding: 60px 50px;
  	}
  .container-book {
  padding: 20px 10px;
  }
  .bg-grey {
  	background-color: #f6f6f6;
  	}
  .person {
  	border: 10px solid transparent;
  	margin-bottom: 25px;
  	width: 50%;
  	height: 50%;
  	opacity: 1;
  	}	
  .person:hover {
  	border-color: #f1f1f1;
  	}
  .jumbotron {
      padding: 100px 25px;
      font-family: Montserrat, sans-serif;
    }
  .logo-small {
      font-size: 50px;
  	}
  .logo {
      font-size: 200px;
  	}
  @media screen and (max-width: 768px) {
      .col-sm-4 {
      text-align: center;
      margin: 25px 0;
      }
    }
  .carousel-control.right, .carousel-control.left {
      background: none !important;
  	filter: progid:none !important;
      color: #000000;
  }
  .carousel-indicators li {
      background-color: #999 !important;
      background-color: rgba(70,70,70,.25)!important;
  }
  .carousel-indicators li.active {
      background-color: #444 !important;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }

  </style>
</head>

<body>
<div class="container">
	<%= render 'layouts/header' %>
	<%= render 'layouts/messages' %>
	<%= yield %>
</div>

<script type="text/javascript">
  $('.alert').delay(7000).fadeOut();
 </script>
</body>

<footer class="container-fluid text-center">
  <br>
  <p><%= t('Website_Made_By')%> Elisabeth & Maxime </p>
</footer>

</html>

app/views/users/index.html.erb
<!-- All Users-->
<div class="container-book bg-grey ">
  <h1><%= t('Listing_Users') %></h1>
</div>

<hr/>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>  

  <tbody>
    <% @users.each do |f| %>
      <tr>
        <td><%= f.email %></td>
         <td><%= link_to t('Show'), f, class: 'btn btn-mini btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<hr />

<h2><%= t('Book_read') %></h2>
<%= render @books %>

<br>
<%= link_to t('Back'), users_path %>